language: ruby
rvm:
  - 2.2.3

sudo: false
cache: bundler
git:
  submodules: false

script: 
  - bundle exec jekyll build
  - bundle exec tests/test.rb
  - bundle exec jekyll test

notifications:
  email:
    recipients:
      - elaine.kamlley@gsa.gov
      - gregory.boone@gsa.gov
    on_success: change
    on_failure: change

branches:
  only:
    - staging
