# Site settings
title: "18F: Digital service delivery"
description: "A fresh start for 18f.gsa.gov"
baseurl: "" # the subpath of your site, e.g. /blog
permalink: pretty
url: "https://beta.18f.gov" # the base hostname & protocol for your site
logo: /assets/img/logos/18F-Logo-Bright-S.png
feature_image: /assets/img/feature-background.jpg
tag_dir: tags

analytics:
  google:
    code: '' # Change this to your GSA analytics code
  dap:
    agency: GSA    # Change this to your agency
    subagency: 18F # Change this to your agency

# blog archive at /blog
paginate: 5
paginate_path: "blog/page/:num"

jekyll-archives:
  enabled:
    - 'tags'
  layout: tag-results
  permalinks:
    tag: '/tags/:name/'

collections:
  team:
    permalink: /team/:name/
    output: true
  cards:
    output: true
    permalink: /card/:name/
  press:
    output: true
    permalink: /press/:name/

defaults:
 -
  scope:
    type: "posts" # an empty string here means all files in the project
  values:
    layout: post
 -
  scope:
    path: "pages"
  values:
    layout: default-intro
 -
  scope:
    path: "team"
  values:
    layout: page

forms:
- type: newsletter
  heading: Sign up to receive updates from our team
  url: https://docs.google.com/forms/d/1Tsdm_2spbxWnmTFMrH5eHxpOAN9W4LB3eaMMXJ1N0rU/formResponse
  button: Subscribe
  privacypolicy: Your privacy and security are important to us, we'll only share your information as described in the <a href="http://www.gsa.gov/portal/content/116609">GSA Privacy and Security Notice</a>
  fields:
    - type: email
      name: entry.1440502332
      label: Email Address
    - type: hidden
      name: fbzx
      value: -7861934959779167198

footer:
  image: /assets/img/logos/18F-Logo-M.png
  email:
  twitter:
    - 18f
    - usgsa
  text: This site was built using <a href="https://federalist.18f.gov/" target="_blank">Federalist, from 18F</a>. # Change to a tag line for your agency

# Build settings
markdown: kramdown
include:
  - _navigation.json
exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md

# jekyll plugins
gems:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-feed

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
